spring.application.name=Quiz-Backend-System

# ===============================
# = DATA SOURCE
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/quizzes
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=quizzes-db
spring.datasource.password=123098123098Kk

# ===============================
# = JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
